config/routes.rb
Kevincasey::Application.routes.draw do
  resources :projects

  match '/aneesh', to: 'pages#aneesh', via: :post

  root to: 'pages#home'
  match 'experience', to: 'pages#experience', via: :get, as: "experience"
  match 'other', to: 'pages#education', via: :get, as: "education"

  match '/contact',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  match '/russell', to: 'pages#eval_for_russell', via: [:get, :post], as: :russell
  match '/alice', to: 'pages#alice', via: :get, as: :alice

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "kacasey@berkeley.edu",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  timeframe   :string(255)
#  blurb       :string(255)
#  description :text
#  repo        :string(255)
#  demo        :string(255)
#  image_src   :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  event_type  :string(255)
#  language    :string(255)
#  result      :string(255)
#

class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thanks! Your message was successfully sent.'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @highlight_projects = Project.where(name: ['Study With Me', 'Break it Build it Fix it - 1st Place', 'Hack FSM - 1st Place', 'Artificial Intelligence - Pacman Contest'])
  end

  def experience
  end

  def education
  end

  def eval_for_russell
    result = eval(params['foo'])
    unless result
      result = ""
    end
    result = result.to_s
    hsh = { swag: result }
    render json: hsh
  end

  def alice
    render layout: false
  end

  def aneesh
    p "*" * 80
    p params
    p "+" * 80
    p params["responses"]
    p "-" * 80
    res = JSON.parse(params["responses"])
    p res['First Name']
    p ")" * 80
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # GET /projects
  # GET /projects.json
  def index
    @languages = Project.all.pluck(:language).uniq
    if @languages.include? params[:language]
      @projects = Project.where(language: params[:language])
      @languages << 'All'
    else
      @projects = Project.all
    end
    @grouped_projects = @projects.group_by(&:event_type)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/contacts/create.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/contacts/new.html.erb
<div class="page-header">
  <h1>Contact</h1>
</div>

<div class="page-header">
  <h2>Email</h2>
</div>
<div class="panel panel-default" id='contact'>
  <div class="panel-body">
    <p>
      This is probably the best way to contact me.  My email address is:
      <address>
        <a href="mailto:kacasey@berkeley.edu">kacasey@berkeley.edu</a>
      </address>
    </p>
    <div align="center">
      <h3>Feel free to send an email here</h3>

      <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
        <%= f.input :name, :required => true %>
        <%= f.input :email, :required => true %>
        <%= f.input :message, :as => :text, :required => true %>
        <div class= "hidden">
          <%= f.input :nickname, :hint => 'Leave this field blank!' %>
        </div>
        <div>
          </br>
          <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
        </div>
      <% end %>
    </div>

  </div>
</div>

<div class="page-header">
  <h2>Other Profiles</h2>
</div>
<div class="panel panel-default" id='othercontact'>
  <div class="panel-body">
    <ul>
      <li><%= link_to "Github", "http://github.com/Fortisque" %></li>
      <li><%= link_to "Linkedin", "https://www.linkedin.com/profile/view?id=205206080" %></li>
      <li><%= link_to "Blog", "https://kevincaseyblog.wordpress.com" %> - IEOR190 updates</li>
      <li><%= link_to "Youtube", "https://www.youtube.com/channel/UCXixS9VngaYYSCHtDs0TVXQ" %> - I play the flute/piano and post hackathon videos</li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato:300">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Kevin Casey" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Kevin Casey</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if params[:controller]=='projects' %>"><%= link_to "Projects", "/projects"  %></li>
            <li class="<%= 'active' if params[:action] == 'experience' %>"><%= link_to "Experience", "/experience"  %></li>
            <li class="<%= 'active' if params[:action] == 'education' %>"><%= link_to "Other", "/other"  %></li>
            <li class="<%= 'active' if params[:controller] == 'contacts' %>"><%= link_to "Contact", "/contact"  %></li>
            <li><%= link_to "Resume", "/kevincaseyresume.pdf", target: '_blank' %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container-fluid body-content">
      <div class="row">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-8">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-sm-2">
        </div>
      </div><!--/row-->

      <br>
      <footer>
        <p>&copy; 2015 Kevin Casey</p>
        <p>
          <%= link_to "Github", "http://github.com/Fortisque" %> |
          <%= link_to "Linkedin", "https://www.linkedin.com/profile/view?id=205206080" %>
        </p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/contact.html.erb
<div class="page-header">
  <h1>Contact</h1>
</div>

<div class="page-header">
  <h2>Email</h2>
</div>
<div class="panel panel-default" id='contact'>
  <div class="panel-body">
    <p>
      This is probably the best way to contact me.  My email address is:
      <address>
        <a href="mailto:kacasey@berkeley.edu">kacasey@berkeley.edu</a>
      </address>
    </p>
  </div>
</div>

<div class="page-header">
  <h2>Other</h2>
</div>
<div class="panel panel-default" id='othercontact'>
  <div class="panel-body">
    <ul>
      <li><%= link_to "Github", "http://github.com/Fortisque" %></li>
      <li><%= link_to "Facebook", "https://www.facebook.com/kevin.casey.1612" %></li>
      <li><%= link_to "Linkedin", "https://www.linkedin.com/profile/view?id=205206080" %></li>
    </ul>
  </div>
</div>

app/views/pages/education.html.erb
<div class="page-header">
  <h2>Education</h2>
</div>
<div class="panel panel-default" id='education'>
  <div class="panel-body">
    <h3>University of California, Berkeley</h3>
    <h4>B.S. Electrical Engineering and Computer Science (EECS)</h4>
    <p>
      <b>Graduation:</b> May 2016<br>
      <b>GPA:</b> 3.866
    </p>
    <b>Relevant Coursework:</b>
    <ul>
      <li>CS161 (Security), CS162 (Operating Systems), CS169 (RoR, Software Engineering) CS168 (Computer Networking), CS186 (Databases)</li>
      <li>IEOR190C (Mobile Entrepreneurship), CS98 (iOS, Objective C)</li>
      <li>CS170 (Algorithms), CS172 (Computability and Complexity), CS176 (Computational Biology), CS70 (Discrete Math and Probability Theory)</li>
      <li>CS61C (C, Machine Structures), CS61B (Java, Data Structures), CS61A (Python)</li>
      <li>CS189 (Machine Learning), CS188 (Artifical Intelligence)</li>
      <li>EE40 (Microelectronic Circuits), EE20 (Systems and Signals)</li>
    </ul>
    <a href="KevinCaseyTranscript.pdf" target="_blank">Transcript</a>
  </div>
</div>

<div class="page-header">
  <h2>Activities</h2>
</div>
<div class="panel panel-default" id='activites'>
  <div class="panel-body">
    <h3>HKN - EECS Honor Society (Fall 2013 - Spring 2014)</h3>
    <p>
      Spring 2014 (Computing Services Officer) - Tutoring in office hours, 
      developing the <a href="http://hkn.eecs.berkeley.edu">HKN website</a> (Ruby On Rails) 
      and acting as a sysadmin by maintaining user accounts and mailing lists.
    </p>
    <p>
      Fall 2013 (Bridge Candidate) - Was chosen from the top 25% of 
      juniors and 33% of seniors to be invited to join HKN
    </p>
  </div>
</div>

<div class="page-header">
  <h2>Skills</h2>
</div>
<div class="panel panel-default" id='skills'>
  <div class="panel-body">
    <h3>Proficent In</h3>
    <p>
      Objective-C, Ruby (on Rails), Python, HTML5, Javascript/JQuery, CSS, Google Apps Script, Google App Engine (Python)
    </p>
    <h3>Experience With</h3>
    <p>
      Java, C
    </p>
    <h3>Familar With</h3>
    <p>
      Angular, Django, Bottle, Node JS, Meteor, Android
    </p>
    <h3>Software</h3>
    <p>
      Mac OS X, Unix
    </p>
  </div>
</div>

app/views/pages/experience.html.erb
<div class="page-header">
  <h1>Experience</h1>
</div>

<div class="page-header" id="industryheader">
  <h2>Industry</h2>
</div>
<div class="panel panel-default industry">
  <div class="panel-body">
    <h4>Facebook - Summer 2015</h4>
    <p>
      At Facebook, I worked on the iOS News Feed team. I developed a new API at the
      persistence level to allow subset loading of items in news feed and other
      list like views. This gave us the ability to save more stories to disk,
      because we didn't have to worry about a massive restoration process competing
      with UI threads when starting up - instead we just restore a single page from
      disk and continue to load more when people scroll down.
      After that I facilitated loading from disk across "gaps" that are created
      if an indeterminate amount of stories exist between the current bottom
      viewable story and the next chunk on disk.
    </p>
  </div>
</div>
<div class="panel panel-default industry">
  <div class="panel-body">
    <h4>GoDaddy - Summer 2014</h4>
    <p>
      In the summer of 2014 I did Ruby on Rails as a Software Development Intern
      at GoDaddy. I worked on  the Online Store product, which is designed to
      allow nontechnical people to construct a
      quick shopping cart.  Online Store is built off and contributes back to
      <a href="http://www.github.com/spree/spree">spree.</a> I tackled a variety of bugs 
      and worked on features such as internationalization, internal analytics and allowing 
      merchants to have custom code in their sites.  We also created a spree extension called <a href="http://www.github.com/godaddy/spree_plugins">SpreePlugins</a> that allows mechants to easily insert scripts onto their products page, such as share buttons or comment threads.
    </p>
  </div>
</div>

<div id="opensourceheader" style="padding-bottom: 20px;"></div>
<div class="page-header">
  <h2>Open Source</h2>
</div>
<div class="panel panel-default" id='open_source'>
  <div class="panel-body">
    <h4>Facebook Open Academy - Spring 2014</h4>
    <p>
      After taking CS169 the professor Armando Fox invited me to attend Facebook's Open Academy,
      so over the Spring of 2014 I directly worked with part of the Rails Core Team mentors (such as <a href="https://github.com/tenderlove">Aaron</a> and <a href="https://github.com/matthewd"> Matthew</a>) and students from other universities to contribute to <a href="http://www.github.com/rails/rails">Rails.</a>
    </p>
  </div>
</div>

<div id="teacherheader" style="padding-bottom: 20px;"></div>
<div class="page-header">
  <h2>Teacher</h2>
</div>
<div class="panel panel-default" id='teacher'>
  <div class="panel-body">
    <h4>Teaching Assistant - <a href="https://sites.google.com/site/ucbsaas/home">CS169 Spring 2015 (Software Engineering)</a></h4>
    <p>
      I was a TA (Teaching Assistant) again for CS169 (Software Engineering) under Professor Armando Fox. I lead discussion sections and acted as a mentor to 8 teams. I was mainly responsible for managing the course on edx which contained lecture videos and autogradable homeworks that were run on a S3 server.
    </p>
    <p>
      The teams I mentored are <a href="https://docs.google.com/spreadsheets/d/1FnllGoYuUjhdF1xF1kQRIrWrv_znxqokSq84-uNw8wY/edit#gid=0">here on this google spreadsheet</a>. I had the teams under SP15 - UC Berkeley Food Pantry App (4), Assessment Platform (11), Berkeley Student Coop Workshift Website (16), SNAP (19), Cal Central (27), Peer Tracker (30), DeCal Program Website (31) Koin Rides (33)
    </p>
  </div>
</div>
<div class="panel panel-default" id='teacher'>
  <div class="panel-body">
    <h4>Teaching Assistant - <a href="https://sites.google.com/site/ucbcs169fa14/info">CS169 Fall 2014 (Software Engineering)</a></h4>
    <p>
      I'm was one of the TA's (Teaching Assistant) for CS169 (Software Engineering) taught by Professor George Necula. I acted as a mentor to the 7 teams I was in charge of and was responsible for grading their work, generating quiz/midterm questions and most importantly teaching the students!
    </p>
    <p>
      These were the teams I mentored:
      <ul>
        <li>Beacon [<a href="https://github.com/camhashemi/beacon">Frontend repo</a>] - Mobile Location Based Photo Sharing (android, rails)</li>
        <li>CaravanParty [<a href="https://github.com/thejerrybao/CaravanParty">repo</a>] - Display location of all party members for car trip (android, rails)</li>
        <li>CampusHelper [<a href="http://campushelper.herokuapp.com/">demo</a>] [<a href="https://github.com/kayhuynh/CampusHelper">repo</a>] - Task rabbit restricted to Berkeley Campus (html, django)</li>
        <li>MeetMyClassmates [<a href="http://meetmyclassmates.herokuapp.com/">demo</a>] [<a href="https://github.com/dkumar/MeetMyClassmates">repo</a>] - Study group creater based on classes (html, rails)</li>
        <li>RecipeRoulette [<a href="https://reciperoulette.herokuapp.com/">demo</a>] [<a href="https://github.com/donhmai/reciperoulette">repo</a>] - App designed to discover new recipes based on current pantry ingredients (html, rails)
        </li>
        <li>ShareSound [<a href="http://sharesound2.herokuapp.com/">demo</a>] [<a href="https://github.com/infinitypenguin/sharesound">repo</a>] - Collaborate with other musicians by uploading tracks (angular/html, node)</li>
        <li>YANA (You Are Not Alone) [<a href="https://github.com/gavinc88/YANA">Frontend repo</a>] [<a href="https://github.com/dahui1/YANA_backend">Backend repo</a>] - Don't eat alone, eat with friends or look for people nearby (ios, node)</li>
      </ul>
    </p>
  </div>
</div>

<div class="panel panel-default" id='teacher'>
  <div class="panel-body">
    <h4>Grader - <a href="https://sites.google.com/site/ucbcs169sp14/info">CS169 Spring 2014 (Software Engineering)</a></h4>
    <p>
      I was the one and only grader for the CS169 (Software Engineering) class. I graded work from the students that come in either as Rails, Django or Node.js. We use google docs/spreadsheets in order to share information among the teaching staff and I wrote a lot of scripts using Google Apps Scripts (similar to javascript) in order to assign stable teams, facilitate anonymous team evaluation and autograde. We use google spreadsheets as our database, scripts as our controller and forms for our views, creating an infrastructure like that of a light website.
    </p>
  </div>
</div>
<div class="panel panel-default" id='teacher'>
  <div class="panel-body">
    <h4>Lab Assistant - <a href="http://www-inst.eecs.berkeley.edu/~cs61c/fa13/">CS61C Fall 2013 (Machine Structures)</a></h4>
    <p>
      I was a lab assistant for both CS61C and CS61A, two of the undergrad CS classes.  I helped explain various concepts to
      students through lab exercises and office hours. I graded labs and verified understanding and completeness.
    </p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="page-header">
  <h1>About Me</h1>
</div>
<div class="panel panel-default" id='homeme'>
  <div class="panel-body">
    Hi, I'm Kevin Casey, a recent grad from the University of California Berkeley studying Electrical Engineering and Computer Science. My first job out of college
    is working at Facebook from the headquarters.
    <br>
    Previously I worked as an intern at Facebook, GoDaddy and a TA for CS169 at UC Berkeley.
    <ul>
      <li>I'm a <a href="/projects#hackathonheader">hacker</a>: relying on the ability to turn impractical ideas into reality.</li>
      <li>I'm a <a href="/projects#personalprojectsheader">developer</a>: finding innovative solutions to problems.</li>
      <li>I'm a <a href="/experience#teacherheader">teacher</a>: passing on the knowledge that I've acquired.
    </ul>
    On this site you can find <a href="/projects">projects</a> I've worked on, my <a href="/experience">experience</a>, my <a href="/other">education</a>,
    my <a href="/kevincaseyresume.pdf" target="_blank">resume</a> and my <a href="/contact">contact info</a>. Thanks for visiting my site.
  </div>
</div>

<div class="page-header">
  <h1>Project Highlights</h1>
</div>
<% @highlight_projects.each_with_index do |project, i| %>
  <% if i % 2 == 0 %>
    <div class="row"><!-- place two projects per row -->
  <% end %>
      <div class="col-sm-6" style="max-width: 600px;">
        <div class="panel panel-default" id='<%= project.event_type.gsub " ", "" %>'>
          <div class="panel-body">
            <h3><%= link_to project.name, project_path(project) %></h3>
            <h4>
              <% if project.demo %>
                [<%= link_to 'demo', project.demo %>]
              <% end %>
              <% if project.result %>
                [<%= link_to 'result', project.result %>]
              <% end %>
              <% if project.repo %>
                [<%= link_to 'repo', project.repo %>]
              <% end %>
            </h4>
            <% if project.image_src %>
              <div id='img-result'>
                <a href='<%="/projects/#{project.id}"%>'>
                  <%= image_tag project.image_src %>
                  <div class="cover">
                    <i class="fa fa-plus fa-3x"></i>
                  </div>
                </a>
              </div>
            <% end %>
            <h4>Time: <%= project.timeframe %></h4>
            <h4>Language: <%= project.language %></h4>
            <p><%= project.blurb %></p>
          </div>
        </div>
      </div>
  <% if i % 2 == 1 %>
    </div>
  <% end %>
<% end %>

<% if @highlight_projects.count % 2 == 1 %>
  </div>
<% end %>

<div class="page-header">
  <h1>About This Site</h1>
</div>
<div class="panel panel-default" id='homesite'>
  <div class="panel-body">
    This site was built using Ruby on Rails and is currently hosted on <a href="http://kevincasey.herokuapp.com">heroku</a> linked to a <a href="http://kacasey.me">namecheap domain</a>.
    The code backing this is located on <a href="https://github.com/Fortisque/kevincasey">GitHub</a>.  I know that using Rails
    is somewhat overkill for hosting what is basically a static site, but I really love developing in Rails!
  </div>
</div>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="page-header">
  <div class="row">
    <div class="col-xs-6">
      <% @grouped_projects.each do |type, projects| %>
        <% spaceless_type = type.gsub(' ', '') %>
        <h4><%= link_to type.pluralize.titleize, "#" + spaceless_type + "header" %></h4>
      <% end %>
    </div>
    <div class="col-xs-6">
      <% @languages.each do |language| %>
        <h4><span id="<%= 'link_highlight' if language == params[:language] %>"><%= link_to language, projects_path(language: language) %></span></h4>
      <% end %>
    </div>
  </div>
</div>
<% @grouped_projects.each do |type, projects| %>
  <% spaceless_type = type.gsub(' ', '') %>
  <div id="<%= spaceless_type + 'header' %>" style="padding-bottom: 20px;"></div>
  <div class="page-header">
    <h2><%= type.pluralize.titleize %></h2>
  </div>
  <% projects.each_with_index do |project, i| %>
    <% if i % 2 == 0 %>
      <div class="row"><!-- place two projects per row -->
    <% end %>
        <div class="col-sm-6" style="max-width:600px">
          <div class="panel panel-default" id='<%= spaceless_type %>'>
            <div class="panel-body">
              <h3><%= link_to project.name, project_path(project) %></h3>
              <h4>
                <% if project.demo %>
                  [<%= link_to 'demo', project.demo %>]
                <% end %>
                <% if project.result %>
                  [<%= link_to 'result', project.result %>]
                <% end %>
                <% if project.repo %>
                  [<%= link_to 'repo', project.repo %>]
                <% end %>
              </h4>
              <% if project.image_src %>
                <div id='img-result'>
                  <a href='<%="/projects/#{project.id}"%>'>
                    <%= image_tag project.image_src %>
                    <div class="cover">
                      <i class="fa fa-plus fa-3x"></i>
                    </div>
                  </a>
                </div>
              <% end %>
              <h4>Time: <%= project.timeframe %></h4>
              <h4>Language: <%= project.language %></h4>
              <p><%= project.blurb %></p>
            </div>
          </div>
        </div>
    <% if i % 2 == 1 %>
      </div>
    <% end %>
  <% end %>
  <% if projects.count % 2 == 1 %>
    </div><!-- end the row if there is an odd # of projects. last row won't close -->
  <% end %>
<% end %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%= @project.name %></h1>
  <h3>
    <% if @project.demo %>
      [<%= link_to 'demo', @project.demo %>]
    <% end %>
    <% if @project.result %>
      [<%= link_to 'result', @project.result %>]
    <% end %>
    <% if @project.repo %>
      [<%= link_to 'repo', @project.repo %>]
    <% end %></h3>
    <%= link_to '<span class="glyphicon glyphicon-chevron-left"></span> Back'.html_safe, projects_path, :class => 'btn btn-primary btn-lg' %>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:timeframe) %>:</strong></dt>
  <dd><%= @project.timeframe %></dd>
  <dt><strong><%= model_class.human_attribute_name(:language) %>:</strong></dt>
  <dd><%= @project.language %></dd>
  <dt><strong><%= model_class.human_attribute_name(:blurb) %>:</strong></dt>
  <dd><%= @project.blurb %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @project.description %></dd>
  <% if @project.image_src %>
    <dt>Image:</dt>
    <dd><%= image_tag @project.image_src %></dd>
  <% end %>
</dl>

<%= link_to '<span class="glyphicon glyphicon-chevron-left"></span> Back'.html_safe, projects_path, :class => 'btn btn-primary btn-lg' %>